### PR TITLE
cli: handle failure to discharge root macaroon gracefully

### LINKED ISSUE #202: `ua attach` should fail gracefully when root macaroon discharge fails
I just ran `ua attach` without my local contract server running and got:

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/daniel/dev/ubuntu-advantage-client/uaclient/cli.py", line 378, in <module>
    sys.exit(main())
  File "/home/daniel/dev/ubuntu-advantage-client/uaclient/cli.py", line 374, in main
    return args.action(args, cfg)
  File "/home/daniel/dev/ubuntu-advantage-client/uaclient/cli.py", line 214, in action_attach
    contract_client).decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'
```

This is clearly an issue introduced by #185.

### PR DESCRIPTION
**Pull request by OddBloke**
This fixes #202.

### CODE REVIEW

File: uaclient/cli.py [hunk 1]
```diff
@@ -210,8 +210,11 @@ def action_attach(args, cfg):
         return 1
     contract_client = contract.UAContractClient(cfg)
     if not args.token:
-        bound_macaroon = sso.discharge_root_macaroon(
-            contract_client).decode('utf-8')
+        bound_macaroon_bytes = sso.discharge_root_macaroon(
+            contract_client)
+        bound_macaroon = None
```
Comment (powersj) [inline uaclient/cli.py]: should this be declared above the if statement? otherwise I'm fine with this.

Comment (OddBloke) [reply uaclient/cli.py]: Moved.
