### ISSUE TITLE
`ua attach` should fail gracefully when root macaroon discharge fails

### ISSUE THREAD

**Issue by OddBloke** [CanonicalLtd/ubuntu-advantage-client#202]
I just ran `ua attach` without my local contract server running and got:

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/daniel/dev/ubuntu-advantage-client/uaclient/cli.py", line 378, in <module>
    sys.exit(main())
  File "/home/daniel/dev/ubuntu-advantage-client/uaclient/cli.py", line 374, in main
    return args.action(args, cfg)
  File "/home/daniel/dev/ubuntu-advantage-client/uaclient/cli.py", line 214, in action_attach
    contract_client).decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'decode'
```

This is clearly an issue introduced by #185.
